project-code/apphome/urls.py
from django.urls import path
from .views import HomeView

app_name = 'apphome'

urlpatterns = [
    path(r'', HomeView.as_view(), name='home'),
]

project-code/appsrer/urls.py
from django.urls import path
from graphene_django.views import GraphQLView
from .views import RaingageAPIView, PrecipEventAPIView, HomeView, PrecipEventList
from .schema import schema


app_name = 'appsrer'
urlpatterns = [
    path(r'graphql', GraphQLView.as_view(graphiql=True, schema=schema), name='srer_graphql'),
    path(r'api/srer/v1.0/raingages', RaingageAPIView.as_view()),
    path(r'api/srer/v1.0/precipevents', PrecipEventAPIView.as_view()),
    path(r'api/srer/v1.0/precipevents/gagename/<str:gagename>/year/<int:year>', PrecipEventList.as_view()),
]

project-code/appwgew/urls.py
from django.urls import path
from graphene_django.views import GraphQLView
from .views import HomeView
from .views import RaingageAPIView, PrecipEventAPIView #, PrecipEventList
from .schema import schema


app_name = 'appwgew'
urlpatterns = [
    path(r'', HomeView.as_view(), name='home'),
    path(r'api/wgew/v1.0/raingages', RaingageAPIView.as_view()),
    path(r'api/wgew/v1.0/precipevents', PrecipEventAPIView.as_view()),
    path(r'graphql', GraphQLView.as_view(graphiql=True, schema=schema), name='wgew_graphql'),
]

project-code/project/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='EAPI')

urlpatterns = [
    path('', include('apphome.urls', namespace='home')),
    path('srer/', include('appsrer.urls', namespace='srer')),
    path('wgew/', include('appwgew.urls', namespace='wgew')),
    path('apidocs/', schema_view, name='apidocs'),
    path('admin/', admin.site.urls),
]

project-code/apphome/models.py
from django.db import models

# Create your models here.

project-code/appsrer/models.py
from django.db import models

class BaseSrer(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
        db_tablespace = 'srer'


class Raingage(BaseSrer):

    code = models.CharField(null=True, blank=True, max_length=125)

    name = models.CharField(null=True, blank=True, max_length=125)

    latitude = models.DecimalField(null=True, blank=True, max_digits=15, decimal_places=5)

    longitude = models.DecimalField(null=True, blank=True, max_digits=15, decimal_places=5)

    class Meta:
        app_label = 'appsrer'
        verbose_name = 'Raingage'
        verbose_name_plural = 'Raingages'

    def __repr__(self):
        return u'{}'.format(self.id)

    def __str__(self):
        return u'{}'.format(self.name)

    def str(self):
        return self.name


class PrecipEvent(BaseSrer):

    year = models.IntegerField(blank=True, null=True)

    month = models.IntegerField(blank=True, null=True)

    precip = models.DecimalField(blank=True, null=True, max_digits=50, decimal_places=10)

    raingage = models.ForeignKey(Raingage, on_delete=models.CASCADE, db_index=True)

    class Meta:
        app_label = 'appsrer'
        verbose_name = 'Precip Events'
        verbose_name_plural = 'Precip Events'

project-code/appwgew/models.py
from django.db import models

class BaseWgew(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
        db_tablespace = 'wgew'


class Raingage(BaseWgew):

    watershed_id = models.CharField(null=True, blank=True, max_length=5)

    gage_id = models.CharField(null=True, blank=True, max_length=125)

    latitude = models.DecimalField(null=True, blank=True, max_digits=15, decimal_places=5)

    longitude = models.DecimalField(null=True, blank=True, max_digits=15, decimal_places=5)

    elevation = models.IntegerField(null=True, blank=True)

    err = models.DecimalField(null=True, blank=True, max_digits=5, decimal_places=1)

    class Meta:
        app_label = 'appwgew'
        verbose_name = 'Raingage'
        verbose_name_plural = 'Raingages'

    def __repr__(self):
        return u'{}'.format(self.id)

    def __str__(self):
        return u'{}'.format(self.gage_id)

    def str(self):
        return self.name


class PrecipEvent(BaseWgew):

    raingage = models.ForeignKey(Raingage, on_delete=models.CASCADE, db_index=True)

    event_date = models.DateField(blank=True, null=True)

    event_time = models.TimeField(blank=True, null=True)

    duration = models.DecimalField(null=True, blank=True, max_digits=15, decimal_places=5)

    depth = models.DecimalField(null=True, blank=True, max_digits=15, decimal_places=5)

    time_est = models.CharField(null=True, blank=True, max_length=2, default=None)

    class Meta:
        app_label = 'appwgew'
        verbose_name = 'Precip Events'
        verbose_name_plural = 'Precip Events'

project-code/apphome/views.py
from django.views.generic import TemplateView
from django.shortcuts import render

class HomeView(TemplateView):
    template_name = 'index.html'

project-code/appsrer/views.py
from django.views.generic import TemplateView
from rest_framework import generics
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import Raingage, PrecipEvent
from .serializers import RaingageSerializer, PrecipEventSerializer


class HomeView(TemplateView):
    template_name = 'index.html'


class PrecipEventAPIView(APIView):

    def get(self, request, format=None):
        queryset = PrecipEvent.objects.all()
        serializer = PrecipEventSerializer(queryset, many=True)
        return Response(serializer.data)


class RaingageAPIView(APIView):

    def get(self, request, format=None):
        queryset = Raingage.objects.all()
        serializer = RaingageSerializer(queryset, many=True)
        return Response(serializer.data)


class PrecipEventList(generics.ListCreateAPIView):
    serializer_class = PrecipEventSerializer

    def get_queryset(self):
        qs = []

        if 'year' in self.kwargs and 'gagename' in self.kwargs:
            year = self.kwargs['year']
            gagename = self.kwargs['gagename']
            qs = PrecipEvent.objects.filter(year=year, raingage__name=gagename)

        return qs

project-code/appwgew/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from rest_framework import generics
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import Raingage, PrecipEvent
from .serializers import RaingageSerializer, PrecipEventSerializer


class HomeView(TemplateView):
    template_name = 'index.html'

class PrecipEventAPIView(APIView):

    def get(self, request, format=None):
        queryset = PrecipEvent.objects.all()
        serializer = PrecipEventSerializer(queryset, many=True)
        return Response(serializer.data)


class RaingageAPIView(APIView):

    def get(self, request, format=None):
        queryset = Raingage.objects.all()
        serializer = RaingageSerializer(queryset, many=True)
        return Response(serializer.data)


class PrecipEventList(generics.ListCreateAPIView):
    serializer_class = PrecipEventSerializer

    def get_queryset(self):
        qs = []

        if 'year' in self.kwargs and 'gagename' in self.kwargs:
            year = self.kwargs['year']
            gagename = self.kwargs['gagename']
            qs = PrecipEvent.objects.filter(year=year, raingage__name=gagename)

        return qs

project-code/apphome/templates/index.html
<!doctype html>

<html>
    <head>
        <title>EAPI</title>
    </head>

    <body>        
    </body>
</html>

project-code/templates/index.html
{% extends 'layouts/default.html' %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <h2>EAPI</h2>
            <div class="list-group">
                <ul class="nav nav-sidebar">
                    <li><a href="{% url 'home:home' %}" class="list-group-item">Home</a></li>
                    <li><a href="{% url 'admin:index' %}" class="list-group-item">Admin</a></li>
                    <li><a href="{% url 'apidocs' %}" class="list-group-item">API Docs</a></li>
                    <li><a href="{% url 'srer:srer_graphql' %}" class="list-group-item">SRER GraphQL API</a></li>
                    <li><a href="{% url 'wgew:wgew_graphql' %}" class="list-group-item">WGEW GraphQL API</a></li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

project-code/templates/layouts/default.html
{% load staticfiles %}

<!doctype html>

<html>
    <head>
        <title>EAPI</title>

        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

        <style type='text/css'>
            body {
                font-family: 'Roboto', sans-serif;
                padding-top: 50px;
            }
        </style>
    </head>

    <body>
        <div class='container'>
            {% block body %}{% endblock %}
        </div>
    </body>
</html>